### ISSUE TITLE
Wrong version

### ISSUE THREAD

**Issue by randompersononinternet69** [PCBox/PCBox#105]
### What happened?

On PCBox 4.2.4, it references an older version, 4.2.3. 

![image](https://github.com/user-attachments/assets/12eac2e7-6edf-454c-87fc-4510c4008345)

### Configuration file

```ini
(not needed)
```

### Operating system

Windows 10 21H2

### CPU

AMD Ryzen 5 7520U

### PCBox version

v4.2.4

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by fuel-pcbox** [comment]
Oops, that's a bit of a blunder there, apologies.
