### ISSUE TITLE
450MHz Katmai missing

### ISSUE THREAD

**Issue by MaxwellS04** [PCBox/PCBox#125]
### What happened?

On the old versions of PCBox, there is 450MHz Pentium III Katmai processor on CPU selection in Slot 1 machines. In the later versions (likely CPU changes), it is missing. I would like to see that processor readded.

### Configuration file

```ini
N/A
```

### Operating system

Windows 11

### CPU

AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx

### PCBox version

4.2.4

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

There is minimum CPU speed (450MHz) of Pentium III (Katmai family), while PCBox allows the out-of-sync lower CPU speeds.

**Comment by fuel-pcbox** [comment]
Yeah, I'm not sure why that is, it's still in the codebase.
