### ISSUE TITLE
Tyan Trinity 371 Windows 98SE Setup hangs when skipping the creation of a Startup Disk.

### ISSUE THREAD

**Issue by fuel-pcbox** [PCBox/PCBox#32]
**Describe the bug**
Tyan Trinity 371 Windows 98SE Setup hangs when skipping the creation of a Startup Disk.

**To Reproduce**
1. Start Windows 98SE setup, and keep the boot disk in the whole time
2. Skip the creation of a Startup Disk
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - PCBox version: Top of pcbox branch
 - Build information: New Dynarec, 64-bit

**Additional context**
Taking out the floppy disk before it asks about making a Startup Disk or using a different board avoids this bug.

**Comment by Olddantrucker** [comment]
How did you even get that far since there is no setup files to install the main emulator itself?

**Comment by fuel-pcbox** [comment]
@Olddantrucker You were already told how to get the emulator set up in the Discussions tab.

**Comment by fuel-pcbox** [comment]
This no longer happens.
