### ISSUE TITLE
nVidia RIVA Models SVGA bug

### ISSUE THREAD

**Issue by wprball** [PCBox/PCBox#34]
**Describe the bug**
The setup (Windows XP Setup) mostly glitching out in nVidia RIVA Models.

**To Reproduce**
1. Wait on bios
2. Wait on Boot Screen of XP
3. See glitching Setup on this SVGA

**Expected behavior**
The setup always glitched on nVidia RIVA Models

**Screenshots**
![20220403-113807-099](https://user-images.githubusercontent.com/80141462/161427433-f24d4bb9-40eb-4cb0-86cc-5c510194f2bb.png)
![20220403-114100-126](https://user-images.githubusercontent.com/80141462/161427436-72cf1acd-599d-4279-8c67-9cc74a449b07.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - Build information: Dev

**Additional context**
I tried nVidia RIVA 128 model one, but it's glitched out in here, See second one of image.

**Comment by fuel-pcbox** [comment]
The nVidia RIVA 128 is restricted to development builds for a reason. It does not work currently.

EDIT: However, AFAIK, this is a regression. Are you emulating a CPU with SSE by any chance? SSE is known to be a bit buggy ATM.

**Comment by wprball** [comment]
Of course. but, SSE must be buggy RN. I use Intel Celeron (Mendocino).

Here's machine config I got this.
![machineconfig](https://user-images.githubusercontent.com/80141462/163222988-cc46983a-86b8-4edf-80d9-96f98d371d80.png)

Also. Can you fix/cleanup SVGA on this nVidia RIVA cards?

If no/nah. That's okay.

If yes/sure. I am ready.

Sorry for late reply.

**Comment by fuel-pcbox** [comment]
Honestly, it could be a bug with HW acceleration, in which case, there isn't much I can do until I do hardware testing.

**Comment by wprball** [comment]
So, you can fix SVGA on this card? Next time until you do hardware testing. or either you do fixing nVidia RIVA cards.

Could it be that fixing? or cleanup.

**Comment by fuel-pcbox** [comment]
No offense, but what exactly are you trying to say? I can't understand your grammar at all in that comment.

**Comment by NanaMizukiAnother7** [comment]
Closed in 425d69224b6296526e6098b3c14f02959aff6bed, right?
