### ISSUE TITLE
Coreboot BIOSes causes PCBox to crash

### ISSUE THREAD

**Issue by NanaMizukiAnother7** [PCBox/PCBox#40]
**Describe the bug**
Selecting coreboot BIOSes will cause PCBox to close with a error message.

**To Reproduce**
1. Open the machine settings.
2. Select "[i440BX] ASUS P2B-LS (coreboot)" or "[i440BX] ASUS P3B-F (coreboot)"
3. See error

**Expected behavior**
These BIOSes successfully boot.

**Desktop (please complete the following information):**
 - OS: Windows 7 buld 7601 (Service Pack 1)
 - PCBox version: v3.50 GIT-master
 - Build information: NDR/DEV

**Additional context**
I should not use coreboot BIOSes for now.

**Comment by fuel-pcbox** [comment]
That's... odd. They work fine for me. Try a build with NEW_DYNAREC set to n maybe?

**Comment by NanaMizukiAnother7** [comment]
> That's... odd. They work fine for me. Try a build with NEW_DYNAREC set to n maybe?

The old dynamic recompiler also crashes.
