### ISSUE TITLE
Atom N270 - SSE3, SSSE3, NX-bit

### ISSUE THREAD

**Issue by Torinde** [PCBox/PCBox#41]
[Atom N270](https://ark.intel.com/content/www/us/en/ark/products/36331/intel-atom-processor-n270-512k-cache-1-60-ghz-533-mhz-fsb.html) is interesting as:
- supports SSE3 and SSSE3 (last MMX instructions are part of that)
- supports NX-bit (which, along with PAE/PSE and SSE2, allows guest Win8/10 and Win7 May 2018 KB4103718)
- is slower than Pentium 4 and Athlon XP (thus more realistic to emulate performance-wise)
- doesn't support x86-64

One oddity - it supports MOVBE (and maybe other Atom-specific features)

To go along with it is also HD Audio.

And if you consider "All 32-bit Windows" in-scope - only a few items will remain to round it out?
- VT-x/AMD-V - Core Solo U1300 1.07GHz (also SSE3 without x86-64)
- SLAT/EPT (but I didn't find a CPU supporting those that doesn't have x86-64 as well)
- GPU execution on host GPU - maybe by using Mesa/Wine, guest DirectX/OpenGL/Vulkan being executed on host. I assume that would require a custom "guest additions" driver (e.g. [VboxSVGA](https://github.com/PCBox/PCBox/discussions/99) or [virtio](https://github.com/virtio-win/kvm-guest-drivers-windows/pull/943))
- USB 3.x pass-through to host device

**Comment by Torinde** [comment]
Slowest CPUs without x86-64 that I found with:
NX + SSE2
- Pentium M ULV 733J 1.1GHz
- A100 600MHz (does it have NX-bit?)
- Sempron 2600+ 1.6GHz "Palermo" (Socket 754, D0, E3 & E6, 90 nm) SDA2600AIO2BA

NX + SSE3
- Core Solo U1300 1.07GHz (also has VT-x)
- VIA C7 1GHz
- Sempron 2600+ 1.6GHz "Palermo" (Socket 754, D0, E3 & E6, 90 nm) SDA2600AIO2BO

NX + SSSE3
- Atom Z500 800MHz
- Vortex86EX2 600MHz

VT-x + SSSE3
- Atom E620 600MHz

There are some CPUs with SSE2/SSE3 without NX, but most seem to be faster.

**Comment by fuel-pcbox** [comment]
This is VERY premature, you do realize that right?

**Comment by Torinde** [comment]
Sure, I meant it as idea for intermediate step between now and [the below](https://github.com/PCBox/pcbox.github.io#planned-improvements-for-the-future):
![image](https://user-images.githubusercontent.com/97228894/180782692-26bee3e9-9e47-411f-b599-c15b3f435fad.png)

**Comment by Torinde** [comment]
also, if that helps: most of the above are derivatives of the already supported [P6](https://en.wikipedia.org/wiki/P6_(microarchitecture)): Pentium M, A100, Core Solo - just with:
- higher top frequency, but models listed above well below the top Pentium III.
- more cache and instructions

**Comment by Torinde** [comment]
Thanks for adding SSE3 and NX!

Is it feasible to add [PAE](https://github.com/86Box/86Box/discussions/3676)? Even if you keep memory capped below 4GB.

**Comment by fuel-pcbox** [comment]
PAE is already added lmao, it's even in 86Box. Also, it's REQUIRED for NX bit emulation.

**Comment by Torinde** [comment]
Ah, I missed that.

Does the SSE2/3 implementation include?
- [x] CLFSH - separate CPUID flag
- [x] MONITOR / MWAIT - separate CPUID flag
- [x] x87 FISTTP
- Branch hints (executing as NOP)
  - [x] [FS: Jcc](https://en.wikipedia.org/w/index.php?title=X86_instruction_listings&oldid=1236915912#Undocumented_instructions_that_appear_only_in_a_limited_subset_of_x86_CPUs_include)
  - [x] HWNT / HST branch hints

**Comment by fuel-pcbox** [comment]
The branch hints don't matter, CLFLUSH works fine, MONITOR/MWAIT aren't implemented, and I THINK they need APIC emulation??? Not sure.

**Comment by Torinde** [comment]
FISTTP - I assume that's also pending, then?

> The branch hints don't matter

Are they executed as NOP? Or crash, etc.?

**Comment by fuel-pcbox** [comment]
They're executed as NOP. Also, FISTTP is implemented as it's part of SSE3 lmao.

**Comment by Torinde** [comment]
Good. Then very few instructions from pure 32-bit x86 remain:
- [x] SSSE3
- [ ] MOVBE
- [ ] VMX/VT-x
- VIA PadLock
  - [ ] ACE2
  - [ ] PHE (SHA1, SHA256)
  - [ ] PMM

> They're executed as NOP.

Does that apply also to the FS:Jcc undocumented one?

**Comment by fuel-pcbox** [comment]
"Does that apply also to the FS:Jcc undocumented one?"

Yes it does.

**Comment by Torinde** [comment]
- [x] PREFETCHW / PREFETCH from 3DNow! executed as NOP on "Intel Generic" (like on P4 65nm)?

**Comment by Torinde** [comment]
> MONITOR/MWAIT aren't implemented, and I THINK they need APIC emulation?
- https://github.com/86Box/86Box/pull/3192

**Comment by fuel-pcbox** [comment]
MONITOR/MWAIT have been stubbed now

**Comment by Torinde** [comment]
- [ ] APIC - I think it's also the last unsupported requirement for Win10, thus if emulated can enable all 32-bit operating systems to run.

**Comment by fuel-pcbox** [comment]
Yeah, APIC's hard tho, gotta debug that some more. There's already a branch for it tho, feature/apic, it just doesn't work lmao
