### ISSUE TITLE
Hypervisor core

### ISSUE THREAD

**Issue by Torinde** [PCBox/PCBox#46]
In addition to the planned "New optional dynamic recompiler that sacrifices timing accuracy for speed" - is it feasible to add an even faster hypervisor core, for example based on [virt86](https://github.com/StrikerX3/virt86) as discussed at joncampbell123/dosbox-x/issues/1089?

To limit the speed maybe some delaying mechanism can be implemented - to (very) roughly match old CPU capability? Or just force the same host core to do part of the Voodoo 2SLI / 3500SE emulation...

**Comment by fuel-pcbox** [comment]
This kind of emulation core would break Windows 9x on newer processors so I can't add it. Sorry.

**Comment by Torinde** [comment]
There is [patcher9x](https://github.com/JHRobotics/patcher9x) - with that I run all Win9x versions on Ryzen.
Separately virt86 will be useful for other OSes as well.

In any case - can it be added as option, to be turned on by the user only when they are unhappy with the performance (and probably that will be on a slightly older hosts anyway)?

**Comment by Torinde** [comment]
What about having it as option - for higher performance in DOS, OS/2 and others besides Win9x?

**Comment by Torinde** [comment]
Related: 86Box/86Box/issues/3566

**Comment by Torinde** [comment]
Here is Win98 running on Ryzen with patcher9x in VirtualBox:
![image](https://github.com/PCBox/PCBox/assets/97228894/48fcbfc4-92ac-490a-859f-bc4cf84d4890)

**Comment by fuel-pcbox** [comment]
I don't plan on requiring unofficial patches just to run OSes in PCBox, that goes against the goals of hardware accuracy and preservation. Stop pushing for this, it's not going to fucking happen.

**Comment by Torinde** [comment]
Preservation of games and software that are too slow under pure emulation would benefit from hypervised CPU.

Not pushing, but informing. Your call if you want that in or not.

**Comment by fuel-pcbox** [comment]
I already told you no twice.
