### ISSUE TITLE
[ISA] MR BIOS 286 Clone hangs during memory test

### ISSUE THREAD

**Issue by usergithub64** [PCBox/PCBox#54]
**Describe the bug**
[ISA] MR BIOS 286 Clone hangs on memory test at about 3264K. A total of 16384K of memory is installed. If you delete the NVR file, then it is possible to avoid freezing. But on restart it freezes again. Starting the machine in PCBox occurs through 86Box Manager v1.7.4 (Renamed PCBox.exe file to 86Box.exe). With the same settings, starting the machine in 86Box via 86Box Manager v1.7.4 works fine. If you run this machine in PCBox without 86Box Manager v1.7.4, then there is no hangup.

**To Reproduce**
1. Create an [ISA] MR BIOS 286 Clone machine with 16384K memory.
2. Start the machine in PCBox via 86Box Manager v1.7.4.
4. See error.

**Expected behavior**
The machine in PCBox, when started through 86Box Manager v1.7.4, should not freeze, as when starting the machine in 86Box through 86Box Manager v1.7.4.

**Screenshots**
![2023-03-09_181124](https://user-images.githubusercontent.com/58270614/224087821-b0df89e4-318d-4677-b0a2-ef0137de1934.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64 v22H2
 - PCBox v4.0 x64 (PCBox-NDR-Dev-Windows-MINGW64-gha692)
 - Build type: dev, old or new recompiler.

**Comment by fuel-pcbox** [comment]
That's... strange, I haven't changed ANYTHING for the 286 machines...

**Comment by fuel-pcbox** [comment]
This seems more like an issue with your copy of 86Box Manager. Closing.

**Comment by usergithub64** [comment]
The issue is not fixed. PCBox with 86Box Manager still freezes. My copy of 86Box Manager is working properly. 86Box with 86Box Manager works properly. The issue needs to be opened again.

**Comment by fuel-pcbox** [comment]
@usergithub64 It works fine in PCBox without 86Box Manager, but not with 86Box Manager, but it works in 86Box either way, so it's probably some weird esoteric incompatibility between 86Box Manager and PCBox, which I don't know how to fix.
