### ISSUE TITLE
[i440BX] Microsoft Virtual PC 2007 keyboard not working in BIOS

### ISSUE THREAD

**Issue by usergithub64** [PCBox/PCBox#56]
**Describe the bug**
[i440BX] Microsoft Virtual PC 2007 keyboard not working in BIOS. You can enter the BIOS, but you cannot navigate through the settings. At the same time, when you press any key, strange sound signals are heard. Deleting the NVR file does not help. This bug is present when running PCBox.exe and is present when running PCBox via 86Box Manager. On the 86Box on this machine, the keyboard in the BIOS works fine.

**To Reproduce**
1. Create an [i440BX] Microsoft Virtual PC 2007 machine.
2. Start the machine in PCBox.exe or via 86Box Manager v1.7.4.
3. Enter BIOS.
4. See error.

**Expected behavior**
The keyboard in the BIOS should work fine.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64 v22H2
 - PCBox v4.0 x64 (PCBox-NDR-Dev-Windows-MINGW64-gha702)
 - Build type: dev, old or new recompiler.

**Comment by fuel-pcbox** [comment]
Strange, I haven't changed anything in the Virtual PC 2007 or keyboard emulation from 86Box except for stuff that's only enabled for coreboot BIOSes. Try the Qt builds maybe?

**Comment by usergithub64** [comment]
In the PCBox-NDR-Dev-Windows-MINGW64-gha709 build, the keyboard in BIOS [i440BX] Microsoft Virtual PC 2007 already works fine. This is probably due to the recent keyboard controller fixes for the 86Box.
