### ISSUE TITLE
ATI RAGE 3D AGP and PCI and ATI RAGE XL AGP and PCI

### ISSUE THREAD

**Issue by TechGuyC** [PCBox/PCBox#65]
Is your feature request related to a problem? Please describe.
No

Describe the solution you'd like
Add ATI RAGE XL PCI and AGP and Also 
ATI RAGE 3D PCI AND AGP

Describe alternatives you've considered
Nvidia Riva TNT

Additional context

**Comment by fuel-pcbox** [comment]
I have already tried to add ATI RAGE emulation before, and it's impossible without either some heavy reverse engineering or documentation. Closing.

**Comment by Torinde** [comment]
I assume you're aware, but just in case not: MAME seems to mention various Rage and Riva TNT models.

**Comment by fuel-pcbox** [comment]
MAME's emulation is nowhere NEAR as complete as PCBox when it comes to nVidia hardware, AND their Rage emulation has not been tested with their PC drivers, which are also nowhere near as complete as PCBox.
