### ISSUE TITLE
Pcchips M579

### ISSUE THREAD

**Issue by TechGuyC** [PCBox/PCBox#66]
The emulated motherboard Pcchips M579 has 2 Bugs

1-The power supply is AT instead of ATX

2-Sometimes when "Del" is pressed during bios post it dosen't go to the config screen and freezes

**Comment by fuel-pcbox** [comment]
The power supply isn't emulated, for one, for another, the bug report template exists for a reason, please fill it out. If you're on Arch Linux, the freezing when pressing keys is something I already know about, but don't know how to fix.

**Comment by TechGuyC** [comment]
**Describe the bug**

The emulated motherboard Pcchips M579 has 2 Bugs

1-The power supply is AT instead of ATX

2-Sometimes when "Del" is pressed during bios post it dosen't go to the config screen and freezes

**To Reproduce**

Steps to reproduce the behavior:

1-For the Bios post error:
Start the emulator with the Pcchips M579 config,then press Del

2-For the power supply error:
If you are using windows 95,98,ME,XP on the emulator,click on start,
then click the shutdown option and turn off the computer

**Expected behavior**

1-The bios should go to the config when del is pressed

2-The motherboard should power off automatically,because the motherboard
is in the super socket 7 List and all the other super socket 7 motherboards power off automatically

**Screenshots**
Here is what happens when the Del button is pressed:
![image](https://github.com/PCBox/PCBox/assets/130917476/f022565b-f3a1-4195-9f89-72f337cb4bdd)


**Desktop (please complete the following information):**
 - OS: Windows 11
 - PcBox version 4.0
 - Build information: [i386,New Dynarec]

**Additional context**
The "Del" error also happens in the Pcchips M729 motherboard

**Comment by fuel-pcbox** [comment]
Strange, I've never had any issues with PCBox freezing on Windows. Also, the shutdown issue isn't because of power supply emulation, as I already said. It's to do with ACPI.
