### ISSUE TITLE
Mouse speed too fast the moment you open a VM (ANY OS)

### ISSUE THREAD

**Issue by KoghaandSooga** [PCBox/PCBox#70]
**Describe the bug**
Mouse uncontrollilbe the moment you turn the dam thing on.
**To Reproduce**
Setup VM and Select Input then start VM to a moment you can use the mouse.

**Expected behavior**
Control the mouse at a consiste speed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 -PCBOX V4.0

**Additional context**
Add any other context about the problem here. If you are using an Optimized build, make sure to try the regular build too before filing a bug report!

**Comment by KoghaandSooga** [comment]
Update: After installing an OS and close it down it will not reboot. It shows a blank screen even though you can hear it try to start up forcing a crash exit.  PCBOX still has a very long ways to go. I hope the author didn't get COVID.  I think people when they develop something should also have a backup plan to handle their 'dead' account if something fatal ever happens to that author so their friends/family can notify and perhaps delete the dead account ESPECIALLY if anything serious is being done with it.

**Comment by fuel-pcbox** [comment]
My account isn't dead, and this project is updated often. I have no idea why you think it isn't. Also, I can't reproduce ANY of your issues. It all works completely fine for me.

**Comment by fuel-pcbox** [comment]
Also, you have not provided NEARLY enough information, neither about the build you're running, the host OS, or in fact, the guest OSes you're running.
