### ISSUE TITLE
PCI Graphics Card Issue in Pcchips M579 and M729

### ISSUE THREAD

**Issue by TechGuyC** [PCBox/PCBox#73]
**Describe the bug**
When i Use a PCI Graphics Card on Pcchips M579 and M729,It makes some beeps and does not display anything on the screen

**To Reproduce**

1.Choose Pcchips M579 (Super Socket 7) or M729 (Slot 1),then choose a PCI Graphics Card for Video 1

**Expected behavior**
The Motherboard should display video

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows 11
 - PcBox version: v4.0 
 - Build information: [x86_64, New Dynarec]

**Additional context**
The Problem Does not happen with Nvidia RIVA 128

**Comment by fuel-pcbox** [comment]
That's... bizarre, the RIVA 128 is very incomplete, so I'm not sure why it would be the only card that works for you. I also haven't changed these machines from 86box, so maybe check to see if the bug happens there as well?

**Comment by TechGuyC** [comment]
I tried the latest version of 86box and also had the bug

**Comment by fuel-pcbox** [comment]
Then report this issue to them instead lol
