### ISSUE TITLE
Windows 7 gets stuck on a black screen on Coppermine and Katmai systems

### ISSUE THREAD

**Issue by SylveonTribe** [PCBox/PCBox#8]
**Describe the bug**
The login windows on Windows 7 doesn't seem to load on a Pentium III (Both Coppermine and Katmai) or Celeron Coppermine system, it will just stay as a black screen with a mouse cursor and do nothing more, on the Mendocino Celeron the same happens but you will get the login window loading after a few minutes.

**To Reproduce**
1. Install Windows 7 (tested this on build 7000 and 7048) on a Penitum III 

**Expected behavior**
The Login Windows loads just like always

**Screenshots**
![image](https://user-images.githubusercontent.com/24677730/135332069-e88d386c-c280-45ce-9463-fbf5f081ad84.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1
 - Build type: Dev

**Additional context**
I tested this with a 533 MHz Celeron Mendocino, a 533 MHz Pentium III Coppermine ,a 533 MHz Celeron Coppermine and a 533 MHz Pentium 3 Katmai and the Pentium III Coppermine, the Pentium III Katmai and the Celeron Coppermine show this behaviour

**Comment by qeeg** [comment]
Does this happen on Windows 7 RTM, and if so, are you able to install it on Pentium 3? I've been having issues getting it installed on a Pentium 3 system in PCBox.

**Comment by fuel-pcbox** [comment]
I finally got Windows 7 to install on a Pentium 3 in my local branch, but I'm still having the issue described by you.
