### ISSUE TITLE
2 mentions of "86Box" in PCBox

### ISSUE THREAD

**Issue by randompersononinternet69** [PCBox/PCBox#92]
### What happened?

1. A dialog showing that I copied the files of PCBox to a different location, but refers to itself as 86Box
2. The configuration file is "86box.cfg", not "pcbox.cfg"/"PCBox.cfg"

### Configuration file

```ini
Uhh, do I actually need to provide the config for this type of issue?
```

### Operating system

Windows 10 22H2

### CPU

AMD Ryzen 5 7520U

### PCBox version

v4.2 (PCBox doesn't show the build for some reason)

### Build architecture

Windows - x64 (64-bit)

### Build type

- [X] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

Not sure if these changes are even necessary, just made this issue to let you decide.

**Comment by fuel-pcbox** [comment]
The first issue is noted, but the second is intentional, so that you can use existing 86Box managers without much fuss.
